version: v1

labels:
  - label: 'enhancement'
    matcher:
      title: '^feat.*?:'

  - label: 'fix'
    matcher:
      title: '^fix.*?:'

  - label: 'documentation'
    matcher:
      title: '^docs.*?:'
      files: ['README.md', 'docs/**']

  - label: 'chore'
    matcher:
      title: '^chore.*?:'

  - label: 'dependencies'
    matcher:
      files: ['package-lock.json']

  - label: 'i18n'
    matcher:
      files: ['app/common/public/locales/**']
