import appiumConfig, {defineConfig, ignorePatterns} from '@appium/oxc-config/oxlint';

export default defineConfig({
  extends: [appiumConfig],
  ignorePatterns: [...ignorePatterns],
  overrides: [
    {
      files: ['**/*.{js,mjs,cjs,jsx,mjsx,ts,tsx,mtsx}'],
      plugins: ['react', 'vitest'],
      env: {
        browser: true,
        vitest: true,
      },
      rules: {
        'react/exhaustive-deps': 'warn',
        'react/hook-use-state': 'error',
        'react/jsx-curly-brace-presence': ['error', {props: 'never', children: 'never', propElementValues: 'always'}],
        'react/jsx-filename-extension': ['error', 'as-needed'],
        'react/jsx-fragments': 'error',
        'react/jsx-handler-names': 'error',
        'react/jsx-key': 'error',
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-constructed-context-values': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-no-script-url': 'error',
        'react/jsx-no-target-blank': 'error',
        'react/jsx-no-undef': 'error',
        'react/jsx-no-useless-fragment': 'error',
        'react/jsx-pascal-case': 'error',
        'react/jsx-props-no-spread-multi': 'error',
        'react/no-array-index-key': 'error',
        'react/no-children-prop': 'error',
        'react/no-clone-element': 'error',
        'react/no-danger': 'error',
        'react/no-did-update-set-state': 'error',
        'react/no-react-children': 'error',
        'react/no-this-in-sfc': 'error',
        'react/no-unescaped-entities': 'error',
        'react/no-unknown-property': 'error',
        'react/no-unsafe': ['error', {checkAliases: true}],
        'react/prefer-function-component': 'error',
        'react/rules-of-hooks': 'error',
        'react/self-closing-comp': 'error',
        'react/style-prop-object': 'error',
        'react/void-dom-elements-no-children': 'error',

        'vitest/expect-expect': 'error',
        'vitest/hoisted-apis-on-top': 'error',
        'vitest/no-commented-out-tests': 'error',
        'vitest/no-conditional-expect': 'error',
        'vitest/no-conditional-tests': 'error',
        'vitest/no-disabled-tests': 'error',
        'vitest/no-focused-tests': 'error',
        'vitest/no-standalone-expect': 'error',
        'vitest/require-to-throw-message': 'error',
        'vitest/valid-describe-callback': 'error',
        'vitest/valid-expect': 'error',
        'vitest/valid-expect-in-promise': 'error',
        'vitest/valid-title': 'error',
        'vitest/warn-todo': 'error',
      },
    },
  ],
});
