# Automatically applies one or more labels to a PR

name: Auto-Labeler
on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches: [main]

jobs:
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v5.0.0
